### ISSUE TITLE
Set and manage timers for each recipe step within the app.

### ISSUE THREAD

**Issue by Jeril1995** [notBASIL/Final-Project#17]

**Comment by eminjaison** [comment]
As a user, I want to be **able to set and manage timers for each recipe** step within the app so that I can easily keep track of cooking times and ensure precise timing during the cooking process.

**Comment by notBASIL** [comment]
As a user, I want to be able to **set and manage timers for each recipe step within the app** so that I can easily keep track of cooking times and ensure precise timing during the cooking process.

**Comment by notBASIL** [comment]
The feature requires more time as it requires keen attention on each recipe, identify time for each step and then implement it.
