### ISSUE TITLE
Adjust ingredient quantities based on desired serving sizes.

### ISSUE THREAD

**Issue by Jeril1995** [notBASIL/Final-Project#18]
As a user, I want to be able to **adjust ingredient quantities** based on the desired serving sizes so that I can easily modify recipes to cater to the number of people I am cooking for.

**Comment by eminjaison** [comment]
As a user, I want to be able to **adjust ingredient quantities based on the desired serving sizes** so that I can easily modify recipes to cater to the number of people I am cooking for.
