### ISSUE TITLE
Share recipes with others via email, messaging apps, or social media.

### ISSUE THREAD

**Issue by Jeril1995** [notBASIL/Final-Project#19]
As a user, I want to be able to **share recipes with others** via email, messaging apps, or social media, so that I can easily share my favorite recipes or culinary creations with friends, family, or fellow cooking enthusiasts.

**Comment by eminjaison** [comment]
As a user, I want to be able to **share recipes with others via email, messaging apps, or social media**, so that I can easily share my favourite recipes or culinary creations with friends, family, or fellow cooking enthusiasts.
