### ISSUE TITLE
Allowing the user to save their favorite recipes to their recipe box

### ISSUE THREAD

**Issue by Jeril1995** [notBASIL/Final-Project#2]

**Comment by eminjaison** [comment]
s a user, I want to be able to **save my favourite recipes** to my recipe box.

**Comment by notBASIL** [comment]
As a user, I would **save my favourite recipes** to see it first.

**Comment by notBASIL** [comment]
This issue isn’t done because, I couldn't figure out the what's with the output display. Logic is written, every other function is been implemented. Moving onto next sprint just not to make it late submission.
