### ISSUE TITLE
Allowing the user to categorize their saved recipes by cuisine

### ISSUE THREAD

**Issue by Soorajmanu123** [notBASIL/Final-Project#24]
As a user i want to be able to **categorize their saved recipes by cuisines**

**Comment by notBASIL** [comment]
Encountered some bug while the time we run it for final recording, so labelling as bug to fix it later and not to count as late submission. The code for the same is already implemented and was working smoothly before.

**Comment by Jeril1995** [comment]
Bug Resolved
