### ISSUE TITLE
Allowing the user to create a grocery list from the ingredients in their saved recipes.

### ISSUE THREAD

**Issue by Jeril1995** [notBASIL/Final-Project#5]

**Comment by eminjaison** [comment]
As a user, I want to be able to **create a grocery list based on the ingredients in my saved recipes.**

**Comment by notBASIL** [comment]
As a user, I want to be able to **create a grocery list** based on the ingredients in my saved recipes.

**Comment by notBASIL** [comment]
This issue isn’t done because, to create the grocery list I've to include all the ingredients in a recipe not just 2 or 3. So I've work it from the recipe adding form to increase slot for all ingredients which was little complicated. So moving this onto next sprint
